export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR';

export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_CHANGE_ITEM_QUANTITY = 'CART_CHANGE_ITEM_QUANTITY';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_INFO_UPDATE = 'LOGIN_INFO_UPDATE';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAIL = 'REGISTER_REQUEST_FAIL';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_REQUEST_SUCCESS = 'USER_DETAILS_REQUEST_SUCCESS';
export const USER_DETAILS_REQUEST_FAIL = 'USER_DETAILS_REQUEST_FAIL';

export const USER_UPDATE_DETAILS_REQUEST = 'USER_UPDATE_DETAILS_REQUEST';
export const USER_UPDATE_DETAILS_REQUEST_SUCCESS = 'USER_UPDATE_DETAILS_REQUEST_SUCCESS';
export const USER_UPDATE_DETAILS_REQUEST_FAIL = 'USER_UPDATE_DETAILS_REQUEST_FAIL';